package handlers

import (
	_ "pvz-service/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title backend service
// @version 1.0.0
// @description Сервис для управления ПВЗ и приемкой товаров

// @securityDefinitions.apikey bearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
// @scheme bearer
// @bearerFormat JWT

// @BasePath /
func RegisterSwagger(e *echo.Echo) {
	e.GET("/swagger/*", echoSwagger.WrapHandler)
}
